# This file was generated by GoReleaser. DO NOT EDIT.
class Coralcert < Formula
  desc "Secret Generation for The Coral Project's Talk product."
  homepage "https://github.com/coralproject/coralcert"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/coralproject/coralcert/releases/download/v1.0.1/coralcert_v1.0.1_darwin_amd64.tar.gz"
    sha256 "5ac525674ff559296f8f2e41e6624cd0071bf2b46e46f6fe514a7f30e1092d58"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/coralproject/coralcert/releases/download/v1.0.1/coralcert_v1.0.1_linux_amd64.tar.gz"
      sha256 "1f836cd1d1b4edec85167df7955feb5b47ce40103fdb5cf7710c71af3a9e963f"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/coralproject/coralcert/releases/download/v1.0.1/coralcert_v1.0.1_linux_arm64.tar.gz"
        sha256 "1fe10defcf4ae171fb39936b4ef136fb11d4b9c450667f978cc8c1b6ea429511"
      else
      end
    end
  end

  def install
    bin.install "coralcert"
  end

  test do
    system "#{bin}/coralcert -v"
  end
end
